var GAME_LEVELS = [
  ["x!!!!!!!!xxxx!x!x!xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x                                                                                                                  x",
   "x    ! !                                                                                                           x",
   "x                                                                                                                  x",
   "x                                                                                                                  x",
   "x          xxx xxx                                                                                                 x",
   "x         ox  o  x                                                                                                 x",
   "x         xx    =x                                                                                                 x",
   "x          x     x                                                                                                 x",
   "x    |o|   x=    x                                                                                                 x",
   "x    !x!   x     x                                                                                                 x",
   "x          x     x                                                                                                 x",
   "x         ox  o  x                                                                                                 x",
   "x         xx  x  x                                                                                                 x",
   "x          x =   x                                                                                                 x",
   "x          x  =  x                                                                                                 x",
   "x     o    x   = x                                                                                                 x",
   "x    !x!   x     x                                                                                                 x",
   "x          x  o  x                                                                                                 x",
   "x          x  x  x                                                                                                 x",
   "x         ox     x                                                                                                 x",
   "x         x=   !!                                                                                                  x",
   "x                      x   x                                                                                       x",
   "x@                    x     x                                                                                      x",
   "xxo                   x    =x                                                                                      x",
   "x xxxx        o       x= o  x                                                                                      x",
   "x!!!!!!!!!!!!xxx!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x"],
   
  ["x x                 !                   !                                       x",
   "x x                 !                   !                                       x",
   "x x                 !                   !                                       x",
   "x x     !   !       !                   !                                       x",
   "x x     !   !       !                   !  !      !                             x",
   "x+x@    !   !     o !                   !  !  o   !                             x",
   "x xxxxxx   o     !                      !  !      !                             x",
   "x                !      x       o       !  !      !                             x",
   "x                !         !!!!!xx      ! x!  o   !                             x",
   "x x       o      !     o           o !     !      !                             x",
   "x            xxxx!                 x       !      !                             x",
   "x       !   !       xxxx                  o!      !                             x",
   "x       !o  !          !                xxx!      !                             x",
   "x     x !   !              xx           !  !      !                             x",
   "x                    o                  !  !      !                             x",
   "x                       !  !            !                                       x",
   "x    o                   x              !       o                               x",
   "x  xx                                   !                                       x",
   "x         o          !       xx         !        o                              x",
   "x         o              o              !                                       x",
   "x         o              xx     !!!!!!!!!         o                             x",
   "x         x                   !!!                 xxx                           x",
   "x                       o     !                                                 x",
   "x                       x!    !                          o                      x",
   "x                         !   !                                                 x",
   "x                          !!!!                                                 x",
   "x                                                                               x",
   "x                                                          o                    x",
   "x                                                                               x",
   "x                                                                               x",
   "x                                                                               x",
   "x                                                                               x",
   "x                                                                       o   o   x",
   "x                                                                   x   o o o  x ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!            x   !! o o  xx ",
   "                                                     !!!!!xxxxxxxxxxxxxxxxxxx!!!!",
   "                                                                                 "],
   

   
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "]
   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
